# Generated by Django 3.0.6 on 2020-06-03 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('titulares', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fisica',
            name='dni',
            field=models.IntegerField(verbose_name='Documento Nacional de Identidad'),
        ),
    ]
